New/force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Todo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New/force-app/main/default/objects/Todo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Status fo todo item</description>
    <formula>IF(Date_of_completion__c -  TODAY() &gt; 1, &quot;Later&quot;, 
   IF(Date_of_completion__c -  TODAY() = 1, &quot;Tomorrow&quot;, 
      IF(Date_of_completion__c -  TODAY() = 0, &quot;Today&quot;, 
         IF(Date_of_completion__c -  TODAY() &lt; 0, &quot;Expired&quot;, null))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

New/force-app/main/default/objects/Todo__c/fields/Date_of_completion__c.field-meta.xml
<CustomField>
    <fullName>Date_of_completion__c</fullName>
    <label>Date of completion</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

New/force-app/main/default/objects/Todo__c/fields/IsDone__c.field-meta.xml
<CustomField>
    <fullName>IsDone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status</description>
    <label>IsDone</label>
    <type>Checkbox</type>
</CustomField>

New/force-app/main/default/classes/TodoController.cls
public with sharing class TodoController {
    @AuraEnabled(cacheable=true)
    public static List<Todo__c> getTodoList() {
        return [
            SELECT
                Id,
                Title__c,
                Description__c,
                Priority__c,
                IsDone__c,
                Date_of_completion__c,
                Category__c
            FROM Todo__c
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Todo__c> findTodos(String searchKey) {
        String key = '%' + searchKey + '%';
        return [
            SELECT Id,
            Title__c,
            Description__c,
            Priority__c,
            IsDone__c,
            Date_of_completion__c,
            Category__c
            FROM Todo__c
            WHERE Title__c LIKE :key 
            WITH SECURITY_ENFORCED
            ORDER BY Title__c
            LIMIT 20
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Todo__c getSingleTodo() {
        return [ SELECT
            Id,
            Title__c,
            Description__c,
            Priority__c,
            IsDone__c,
            Date_of_completion__c,
            Category__c
            FROM Todo__c
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Todo__c getSingleTodoById(String idStr) {
        return [ SELECT
            Id,
            Title__c,
            Description__c,
            Priority__c,
            IsDone__c,
            Date_of_completion__c,
            Category__c
            FROM Todo__c WHERE Id =: idStr
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static void updateTodos(List<Todo__c> todoForUpdate) {
        if (!Schema.sObjectType.Contact.isUpdateable()) {
            throw new SecurityException(
                'Insufficient permissions to update TODOs'
            );
        }
        update todoForUpdate;
    }
}