New/force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Todo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New/force-app/main/default/objects/Todo__c/fields/Date_of_completion__c.field-meta.xml
<CustomField>
    <fullName>Date_of_completion__c</fullName>
    <label>Date of completion</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

New/force-app/main/default/objects/Todo__c/fields/IsDone__c.field-meta.xml
<CustomField>
    <fullName>IsDone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status</description>
    <label>IsDone</label>
    <type>Checkbox</type>
</CustomField>

New/force-app/main/default/classes/ToDoControllerTest.cls
@isTest
class ToDoControllerTest {
    @TestSetup
    static void makeData(){
        List<Todo__c>tdList = new List<Todo__c>();
        for(Integer i = 0; i < 10; i++){
            Todo__c one = new Todo__c(Title__c = 't ' + String.valueOf(i),
            Description__c = 'new',
            Priority__c = 'Low',
            IsDone__c = false,
            Date_of_completion__c = Date.newInstance(2022, 15, 3));
            tdList.add(one);
        }
        insert tdList;
    }
    @isTest
    static void getTodoListTest(){
        
        Test.startTest();
        List<Todo__c> res = TodoController.getTodoList();
        Test.stopTest();

        System.assertEquals(10, res.size());
    }
}